const K="meus_gastos_v3",BK="meus_gastos_orcamento";let E=JSON.parse(localStorage.getItem(K)||"[]"),B=JSON.parse(localStorage.getItem(BK)||"{}"),M=new Date().toISOString().slice(0,7),T="variable",C="🍔 Alimentação";
const cats={variable:["🍔 Alimentação","🛒 Mercado","⛽ Transporte","🎮 Lazer","👕 Roupas","💊 Farmácia","🐶 Pet","📦 Outros"],fixed:["🏠 Moradia","⚡ Contas","🌐 Internet","📱 Celular","🎓 Faculdade","🚗 Financiamento","🛡️ Seguro","📺 Assinaturas"]},$=x=>document.getElementById(x),money=n=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n),ml=m=>{let[a,b]=m.split("-");return new Date(+a,+b-1,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})},pm=v=>parseFloat(v.replace(/[^\d,.-]/g,"").replace(/\./g,"").replace(",","."));
function save(){localStorage.setItem(K,JSON.stringify(E));localStorage.setItem(BK,JSON.stringify(B))}
function render(){let L=E.filter(x=>x.date.slice(0,7)==M).sort((a,b)=>b.created-a.created),tot=L.reduce((s,x)=>s+x.value,0),fix=L.filter(x=>x.type=="fixed").reduce((s,x)=>s+x.value,0);$("monthBtn").textContent=ml(M);$("total").textContent=money(tot);$("fixed").textContent=money(fix);$("variable").textContent=money(tot-fix);
$("list").innerHTML=L.length?L.map(x=>`<div class="expense"><div class="icon">${x.category[0]}</div><div class="main"><b>${esc(x.description||x.category.slice(2))}</b><span>${x.type=="fixed"?"Fixa":"Variável"} · ${br(x.date)}</span></div><div class="amount">${money(x.value)}<button class="delete" onclick="del('${x.id}')">Excluir</button></div></div>`).join(""):`<div class="empty">Nenhuma despesa neste mês.<br>Toque em <b>+ GASTO</b> para começar.</div>`;
let b=B[M]||0,avail=b-tot;$("spent").textContent=money(tot);$("available").textContent=b?(avail>=0?"Disponível: "+money(avail):"Acima do orçamento: "+money(-avail)):"Sem orçamento";$("progress").style.width=(b?Math.min(tot/b*100,100):0)+"%";$("progress").classList.toggle("danger",b&&tot>b);
let s={};L.forEach(x=>s[x.category]=(s[x.category]||0)+x.value);let a=Object.entries(s).sort((x,y)=>y[1]-x[1]),mx=a[0]?.[1]||1;$("cats").innerHTML=a.length?a.map(([c,v])=>`<div class="cat"><div class="icon">${c[0]}</div><div class="name">${esc(c.slice(2))}<div class="bar"><i style="width:${v/mx*100}%"></i></div></div><b>${money(v)}</b></div>`).join(""):`<div class="empty">Sem gastos neste mês.</div>`;
let d=new Date(M+"-01T12:00"),ms=[];for(let i=5;i>=0;i--){let q=new Date(d.getFullYear(),d.getMonth()-i,1);ms.push(q.toISOString().slice(0,7))}let vs=ms.map(m=>E.filter(x=>x.date.slice(0,7)==m).reduce((s,x)=>s+x.value,0)),max=Math.max(...vs,1);$("chart").innerHTML=ms.map((m,i)=>`<div class="barcol"><i style="height:${vs[i]/max*120}px" title="${money(vs[i])}"></i><span>${new Date(m+"-01T12:00").toLocaleDateString("pt-BR",{month:"short"}).replace(".","")}</span></div>`).join("")}
function renderCats(){$("categoryButtons").innerHTML=cats[T].map(c=>`<button class="${c==C?"selected":""}" onclick="choose('${c.replace(/'/g,"\\'")}')">${c}</button>`).join("")}
function choose(c){C=c;renderCats()}function br(d){return new Date(d+"T12:00").toLocaleDateString("pt-BR")}function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function del(id){if(confirm("Excluir esta despesa?")){E=E.filter(x=>x.id!=id);save();render()}}
$("addBtn").onclick=()=>{$("modal").classList.remove("hidden");renderCats();$("value").focus()};$("close").onclick=()=>$("modal").classList.add("hidden");
document.querySelectorAll(".toggle button").forEach(b=>b.onclick=()=>{T=b.dataset.t;document.querySelectorAll(".toggle button").forEach(x=>x.classList.toggle("on",x==b));C=cats[T][0];renderCats()});
$("save").onclick=()=>{let v=pm($("value").value);if(!v||v<=0)return alert("Digite um valor válido.");E.push({id:crypto.randomUUID(),value:v,type:T,category:C,description:$("desc").value.trim(),date:M==new Date().toISOString().slice(0,7)?new Date().toISOString().slice(0,10):M+"-01",created:Date.now()});save();$("value").value="";$("desc").value="";$("modal").classList.add("hidden");render()};
$("clearBtn").onclick=()=>{if(confirm("Apagar todas as despesas deste mês?")){E=E.filter(x=>x.date.slice(0,7)!=M);save();render()}};
$("budgetBtn").onclick=()=>{$("budgetModal").classList.remove("hidden");$("budgetValue").value=B[M]?String(B[M]).replace(".",","):""};$("budgetClose").onclick=()=>$("budgetModal").classList.add("hidden");
$("budgetSave").onclick=()=>{let v=pm($("budgetValue").value);if(!v||v<=0)return alert("Digite um orçamento válido.");B[M]=v;save();$("budgetModal").classList.add("hidden");render()};
$("monthBtn").onclick=()=>{$("months").classList.remove("hidden");$("monthList").innerHTML=Array.from({length:12},(_,i)=>{let d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);let m=d.toISOString().slice(0,7);return `<button class="monthOpt ${m==M?"sel":""}" onclick="selMonth('${m}')">${ml(m)}</button>`}).join("")};$("monthsClose").onclick=()=>$("months").classList.add("hidden");
function selMonth(m){M=m;$("months").classList.add("hidden");render()}render();